"""add profiles.goal_weight

Revision ID: 1e4bc2314a86
Revises: afed2f0f1186
Create Date: 2026-04-23 23:51:14.446818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e4bc2314a86'
down_revision: Union[str, Sequence[str], None] = 'afed2f0f1186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('goal_weight', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'goal_weight')
    # ### end Alembic commands ###
