"""drop legacy profile columns: name, age, gym (string)

Revision ID: 1e960f0e451a
Revises: 1e4bc2314a86
Create Date: 2026-04-24 00:34:49.952545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e960f0e451a'
down_revision: Union[str, Sequence[str], None] = '1e4bc2314a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'age')
    op.drop_column('profiles', 'name')
    op.drop_column('profiles', 'gym')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('gym', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
