"""add_is_public_to_workouts

Revision ID: a05a33665353
Revises: c14aeb896a58
Create Date: 2026-05-02 20:36:47.290970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05a33665353'
down_revision: Union[str, Sequence[str], None] = 'c14aeb896a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'is_public')
    # ### end Alembic commands ###
