"""add profile identity, location, athlete fields

Revision ID: afed2f0f1186
Revises: ba6f79922ccc
Create Date: 2026-04-23 23:02:25.326813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afed2f0f1186'
down_revision: Union[str, Sequence[str], None] = 'ba6f79922ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('primary_sport', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('profiles', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('gender', sa.String(length=20), nullable=True))
    op.alter_column('profiles', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('profiles', 'bio',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('profiles', 'gym',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('profiles', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profiles', 'gym',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('profiles', 'bio',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('profiles', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('profiles', 'gender')
    op.drop_column('profiles', 'birthdate')
    op.drop_column('profiles', 'state')
    op.drop_column('profiles', 'primary_sport')
    op.drop_column('profiles', 'profile_picture_url')
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'first_name')
    # ### end Alembic commands ###
